platform :ios, '13.0'
use_frameworks!

target 'AppLinkExample' do
    pod 'VlendingAppLink', :git => 'https://github.com/vlending-dev/applink-ios-sdk.git', :branch => 'develop'
    pod 'Alamofire', '5.8.1'
end
